<template>
  <div data-v-394040b0 class="icons">
    <div
      @click="select(index)"
      v-for="(item, index) in icons"
      :key="index"
      class="icons-item"
    >
      <i
        :class="[item, selectIndex == index ? 'active' : '']"
        style="font-size: 32px"
      ></i>
      <p>{{ item }}</p>
    </div>
  </div>
</template>
<script>
export default {
  props: {
    onSelect: {
      type: Function,
      default: () => {
        return "";
      },
    },
  },
  methods: {
    select(index) {
      this.selectIndex = index;
      this.onSelect(index < 0 ? "" : this.icons[index]);
    },
  },
  data() {
    return {
      selectIndex: -1,
      icons: [
        //ivu-icon ivu-icon-ios-add
        "el-icon-platform-eleme",
        "el-icon-eleme",
        "el-icon-delete-solid",
        "el-icon-delete",
        "el-icon-s-tools",
        "el-icon-setting",
        "el-icon-user-solid",
        "el-icon-user",
        "el-icon-phone",
        "el-icon-phone-outline",
        "el-icon-more",
        "el-icon-more-outline",
        "el-icon-star-on",
        "el-icon-star-off",
        "el-icon-s-goods",
        "el-icon-goods",
        "el-icon-warning",
        "el-icon-warning-outline",
        "el-icon-question",
        "el-icon-info",
        "el-icon-remove",
        "el-icon-circle-plus",
        "el-icon-success",
        "el-icon-error",
        "el-icon-zoom-in",
        "el-icon-zoom-out",
        "el-icon-remove-outline",
        "el-icon-circle-plus-outline",
        "el-icon-circle-check",
        "el-icon-circle-close",
        "el-icon-s-help",
        "el-icon-help",
        "el-icon-minus",
        "el-icon-plus",
        "el-icon-check",
        "el-icon-close",
        "el-icon-picture",
        "el-icon-picture-outline",
        "el-icon-picture-outline-round",
        "el-icon-upload",
        "el-icon-upload2",
        "el-icon-download",
        "el-icon-camera-solid",
        "el-icon-camera",
        "el-icon-video-camera-solid",
        "el-icon-video-camera",
        "el-icon-message-solid",
        "el-icon-bell",
        "el-icon-s-cooperation",
        "el-icon-s-order",
        "el-icon-s-platform",
        "el-icon-s-fold",
        "el-icon-s-unfold",
        "el-icon-s-operation",
        "el-icon-s-promotion",
        "el-icon-s-home",
        "el-icon-s-release",
        "el-icon-s-ticket",
        "el-icon-s-management",
        "el-icon-s-open",
        "el-icon-s-shop",
        "el-icon-s-marketing",
        "el-icon-s-flag",
        "el-icon-s-comment",
        "el-icon-s-finance",
        "el-icon-s-claim",
        "el-icon-s-custom",
        "el-icon-s-opportunity",
        "el-icon-s-data",
        "el-icon-s-check",
        "el-icon-s-grid",
        "el-icon-menu",
        "el-icon-share",
        "el-icon-d-caret",
        "el-icon-caret-left",
        "el-icon-caret-right",
        "el-icon-caret-bottom",
        "el-icon-caret-top",
        "el-icon-bottom-left",
        "el-icon-bottom-right",
        "el-icon-back",
        "el-icon-right",
        "el-icon-bottom",
        "el-icon-top",
        "el-icon-top-left",
        "el-icon-top-right",
        "el-icon-arrow-left",
        "el-icon-arrow-right",
        "el-icon-arrow-down",
        "el-icon-arrow-up",
        "el-icon-d-arrow-left",
        "el-icon-d-arrow-right",
        "el-icon-video-pause",
        "el-icon-video-play",
        "el-icon-refresh",
        "el-icon-refresh-right",
        "el-icon-refresh-left",
        "el-icon-finished",
        "el-icon-sort",
        "el-icon-sort-up",
        "el-icon-sort-down",
        "el-icon-rank",
        "el-icon-loading",
        "el-icon-view",
        "el-icon-c-scale-to-original",
        "el-icon-date",
        "el-icon-edit",
        "el-icon-edit-outline",
        "el-icon-folder",
        "el-icon-folder-opened",
        "el-icon-folder-add",
        "el-icon-folder-remove",
        "el-icon-folder-delete",
        "el-icon-folder-checked",
        "el-icon-tickets",
        "el-icon-document-remove",
        "el-icon-document-delete",
        "el-icon-document-copy",
        "el-icon-document-checked",
        "el-icon-document",
        "el-icon-document-add",
        "el-icon-printer",
        "el-icon-paperclip",
        "el-icon-takeaway-box",
        "el-icon-search",
        "el-icon-monitor",
        "el-icon-attract",
        "el-icon-mobile",
        "el-icon-scissors",
        "el-icon-umbrella",
        "el-icon-headset",
        "el-icon-brush",
        "el-icon-mouse",
        "el-icon-coordinate",
        "el-icon-magic-stick",
        "el-icon-reading",
        "el-icon-data-line",
        "el-icon-data-board",
        "el-icon-pie-chart",
        "el-icon-data-analysis",
        "el-icon-collection-tag",
        "el-icon-film",
        "el-icon-suitcase",
        "el-icon-suitcase-1",
        "el-icon-receiving",
        "el-icon-collection",
        "el-icon-files",
        "el-icon-notebook-1",
        "el-icon-notebook-2",
        "el-icon-toilet-paper",
        "el-icon-office-building",
        "el-icon-school",
        "el-icon-table-lamp",
        "el-icon-house",
        "el-icon-no-smoking",
        "el-icon-smoking",
        "el-icon-shopping-cart-full",
        "el-icon-shopping-cart-1",
        "el-icon-shopping-cart-2",
        "el-icon-shopping-bag-1",
        "el-icon-shopping-bag-2",
        "el-icon-sold-out",
        "el-icon-sell",
        "el-icon-present",
        "el-icon-box",
        "el-icon-bank-card",
        "el-icon-money",
        "el-icon-coin",
        "el-icon-wallet",
        "el-icon-discount",
        "el-icon-price-tag",
        "el-icon-news",
        "el-icon-guide",
        "el-icon-male",
        "el-icon-female",
        "el-icon-thumb",
        "el-icon-cpu",
        "el-icon-link",
        "el-icon-connection",
        "el-icon-open",
        "el-icon-turn-off",
        "el-icon-set-up",
        "el-icon-chat-round",
        "el-icon-chat-line-round",
        "el-icon-chat-square",
        "el-icon-chat-dot-round",
        "el-icon-chat-dot-square",
        "el-icon-chat-line-square",
        "el-icon-message",
        "el-icon-postcard",
        "el-icon-position",
        "el-icon-turn-off-microphone",
        "el-icon-microphone",
        "el-icon-close-notification",
        "el-icon-bangzhu",
        "el-icon-time",
        "el-icon-odometer",
        "el-icon-crop",
        "el-icon-aim",
        "el-icon-switch-button",
        "el-icon-full-screen",
        "el-icon-copy-document",
        "el-icon-mic",
        "el-icon-stopwatch",
        "el-icon-medal-1",
        "el-icon-medal",
        "el-icon-trophy",
        "el-icon-trophy-1",
        "el-icon-first-aid-kit",
        "el-icon-discover",
        "el-icon-place",
        "el-icon-location",
        "el-icon-location-outline",
        "el-icon-location-information",
        "el-icon-add-location",
        "el-icon-delete-location",
        "el-icon-map-location",
        "el-icon-alarm-clock",
        "el-icon-timer",
        "el-icon-watch-1",
        "el-icon-watch",
        "el-icon-lock",
        "el-icon-unlock",
        "el-icon-key",
        "el-icon-service",
        "el-icon-mobile-phone",
        "el-icon-bicycle",
        "el-icon-truck",
        "el-icon-ship",
        "el-icon-basketball",
        "el-icon-football",
        "el-icon-soccer",
        "el-icon-baseball",
        "el-icon-wind-power",
        "el-icon-light-rain",
        "el-icon-lightning",
        "el-icon-heavy-rain",
        "el-icon-sunrise",
        "el-icon-sunrise-1",
        "el-icon-sunset",
        "el-icon-sunny",
        "el-icon-cloudy",
        "el-icon-partly-cloudy",
        "el-icon-cloudy-and-sunny",
        "el-icon-moon",
        "el-icon-moon-night",
        "el-icon-dish",
        "el-icon-dish-1",
        "el-icon-food",
        "el-icon-chicken",
        "el-icon-fork-spoon",
        "el-icon-knife-fork",
        "el-icon-burger",
        "el-icon-tableware",
        "el-icon-sugar",
        "el-icon-dessert",
        "el-icon-ice-cream",
        "el-icon-hot-water",
        "el-icon-water-cup",
        "el-icon-coffee-cup",
        "el-icon-cold-drink",
        "el-icon-goblet",
        "el-icon-goblet-full",
        "el-icon-goblet-square",
        "el-icon-goblet-square-full",
        "el-icon-refrigerator",
        "el-icon-grape",
        "el-icon-watermelon",
        "el-icon-cherry",
        "el-icon-apple",
        "el-icon-pear",
        "el-icon-orange",
        "el-icon-coffee",
        "el-icon-ice-tea",
        "el-icon-ice-drink",
        "el-icon-milk-tea",
        "el-icon-potato-strips",
        "el-icon-lollipop",
        "el-icon-ice-cream-square",
        "el-icon-ice-cream-round",
        "bi-0-circle","bi-0-circle-fill","bi-0-square","bi-0-square-fill","bi-1-circle","bi-1-circle-fill","bi-1-square","bi-1-square-fill","bi-123","bi-2-circle","bi-2-circle-fill","bi-2-square","bi-2-square-fill","bi-3-circle","bi-3-circle-fill","bi-3-square","bi-3-square-fill","bi-4-circle","bi-4-circle-fill","bi-4-square","bi-4-square-fill","bi-5-circle","bi-5-circle-fill","bi-5-square","bi-5-square-fill","bi-6-circle","bi-6-circle-fill","bi-6-square","bi-6-square-fill","bi-7-circle","bi-7-circle-fill","bi-7-square","bi-7-square-fill","bi-8-circle","bi-8-circle-fill","bi-8-square","bi-8-square-fill","bi-9-circle","bi-9-circle-fill","bi-9-square","bi-9-square-fill","bi-activity","bi-airplane","bi-airplane-engines","bi-airplane-engines-fill","bi-airplane-fill","bi-alarm","bi-alarm-fill","bi-alexa","bi-align-bottom","bi-align-center","bi-align-end","bi-align-middle","bi-align-start","bi-align-top","bi-alipay","bi-alt","bi-amd","bi-android","bi-android2","bi-app","bi-app-indicator","bi-apple","bi-archive","bi-archive-fill","bi-arrow-90deg-down","bi-arrow-90deg-left","bi-arrow-90deg-right","bi-arrow-90deg-up","bi-arrow-bar-down","bi-arrow-bar-left","bi-arrow-bar-right","bi-arrow-bar-up","bi-arrow-clockwise","bi-arrow-counterclockwise","bi-arrow-down","bi-arrow-down-circle","bi-arrow-down-circle-fill","bi-arrow-down-left-circle","bi-arrow-down-left-circle-fill","bi-arrow-down-left-square","bi-arrow-down-left-square-fill","bi-arrow-down-right-circle","bi-arrow-down-right-circle-fill","bi-arrow-down-right-square","bi-arrow-down-right-square-fill","bi-arrow-down-square","bi-arrow-down-square-fill","bi-arrow-down-left","bi-arrow-down-right","bi-arrow-down-short","bi-arrow-down-up","bi-arrow-left","bi-arrow-left-circle","bi-arrow-left-circle-fill","bi-arrow-left-square","bi-arrow-left-square-fill","bi-arrow-left-right","bi-arrow-left-short","bi-arrow-repeat","bi-arrow-return-left","bi-arrow-return-right","bi-arrow-right","bi-arrow-right-circle","bi-arrow-right-circle-fill","bi-arrow-right-square","bi-arrow-right-square-fill","bi-arrow-right-short","bi-arrow-through-heart","bi-arrow-through-heart-fill","bi-arrow-up","bi-arrow-up-circle","bi-arrow-up-circle-fill","bi-arrow-up-left-circle","bi-arrow-up-left-circle-fill","bi-arrow-up-left-square","bi-arrow-up-left-square-fill","bi-arrow-up-right-circle","bi-arrow-up-right-circle-fill","bi-arrow-up-right-square","bi-arrow-up-right-square-fill","bi-arrow-up-square","bi-arrow-up-square-fill","bi-arrow-up-left","bi-arrow-up-right","bi-arrow-up-short","bi-arrows-angle-contract","bi-arrows-angle-expand","bi-arrows-collapse","bi-arrows-expand","bi-arrows-fullscreen","bi-arrows-move","bi-aspect-ratio","bi-aspect-ratio-fill","bi-asterisk","bi-at","bi-award","bi-award-fill","bi-back","bi-backspace","bi-backspace-fill","bi-backspace-reverse","bi-backspace-reverse-fill","bi-badge-3d","bi-badge-3d-fill","bi-badge-4k","bi-badge-4k-fill","bi-badge-8k","bi-badge-8k-fill","bi-badge-ad","bi-badge-ad-fill","bi-badge-ar","bi-badge-ar-fill","bi-badge-cc","bi-badge-cc-fill","bi-badge-hd","bi-badge-hd-fill","bi-badge-sd","bi-badge-sd-fill","bi-badge-tm","bi-badge-tm-fill","bi-badge-vo","bi-badge-vo-fill","bi-badge-vr","bi-badge-vr-fill","bi-badge-wc","bi-badge-wc-fill","bi-bag","bi-bag-check","bi-bag-check-fill","bi-bag-dash","bi-bag-dash-fill","bi-bag-fill","bi-bag-heart","bi-bag-heart-fill","bi-bag-plus","bi-bag-plus-fill","bi-bag-x","bi-bag-x-fill","bi-balloon","bi-balloon-fill","bi-balloon-heart","bi-balloon-heart-fill","bi-bandaid","bi-bandaid-fill","bi-bank","bi-bank2","bi-bar-chart","bi-bar-chart-fill","bi-bar-chart-line","bi-bar-chart-line-fill","bi-bar-chart-steps","bi-basket","bi-basket-fill","bi-basket2","bi-basket2-fill","bi-basket3","bi-basket3-fill","bi-battery","bi-battery-charging","bi-battery-full","bi-battery-half","bi-behance","bi-bell","bi-bell-fill","bi-bell-slash","bi-bell-slash-fill","bi-bezier","bi-bezier2","bi-bicycle","bi-binoculars","bi-binoculars-fill","bi-blockquote-left","bi-blockquote-right","bi-bluetooth","bi-body-text","bi-book","bi-book-fill","bi-book-half","bi-bookmark","bi-bookmark-check","bi-bookmark-check-fill","bi-bookmark-dash","bi-bookmark-dash-fill","bi-bookmark-fill","bi-bookmark-heart","bi-bookmark-heart-fill","bi-bookmark-plus","bi-bookmark-plus-fill","bi-bookmark-star","bi-bookmark-star-fill","bi-bookmark-x","bi-bookmark-x-fill","bi-bookmarks","bi-bookmarks-fill","bi-bookshelf","bi-boombox","bi-boombox-fill","bi-bootstrap","bi-bootstrap-fill","bi-bootstrap-reboot","bi-border","bi-border-all","bi-border-bottom","bi-border-center","bi-border-inner","bi-border-left","bi-border-middle","bi-border-outer","bi-border-right","bi-border-style","bi-border-top","bi-border-width","bi-bounding-box","bi-bounding-box-circles","bi-box","bi-box-arrow-down-left","bi-box-arrow-down-right","bi-box-arrow-down","bi-box-arrow-in-down","bi-box-arrow-in-down-left","bi-box-arrow-in-down-right","bi-box-arrow-in-left","bi-box-arrow-in-right","bi-box-arrow-in-up","bi-box-arrow-in-up-left","bi-box-arrow-in-up-right","bi-box-arrow-left","bi-box-arrow-right","bi-box-arrow-up","bi-box-arrow-up-left","bi-box-arrow-up-right","bi-box-fill","bi-box-seam","bi-box-seam-fill","bi-box2","bi-box2-fill","bi-box2-heart","bi-box2-heart-fill","bi-boxes","bi-braces","bi-braces-asterisk","bi-bricks","bi-briefcase","bi-briefcase-fill","bi-brightness-alt-high","bi-brightness-alt-high-fill","bi-brightness-alt-low","bi-brightness-alt-low-fill","bi-brightness-high","bi-brightness-high-fill","bi-brightness-low","bi-brightness-low-fill","bi-broadcast","bi-broadcast-pin","bi-browser-chrome","bi-browser-edge","bi-browser-firefox","bi-browser-safari","bi-brush","bi-brush-fill","bi-bucket","bi-bucket-fill","bi-bug","bi-bug-fill","bi-building","bi-building-add","bi-building-check","bi-building-dash","bi-building-down","bi-building-exclamation","bi-building-fill","bi-building-fill-add","bi-building-fill-check","bi-building-fill-dash","bi-building-fill-down","bi-building-fill-exclamation","bi-building-fill-gear","bi-building-fill-lock","bi-building-fill-slash","bi-building-fill-up","bi-building-fill-x","bi-building-gear","bi-building-lock","bi-building-slash","bi-building-up","bi-building-x","bi-buildings","bi-buildings-fill","bi-bullseye","bi-bus-front","bi-bus-front-fill","bi-c-circle","bi-c-circle-fill","bi-c-square","bi-c-square-fill","bi-calculator","bi-calculator-fill","bi-calendar","bi-calendar-check","bi-calendar-check-fill","bi-calendar-date","bi-calendar-date-fill","bi-calendar-day","bi-calendar-day-fill","bi-calendar-event","bi-calendar-event-fill","bi-calendar-fill","bi-calendar-heart","bi-calendar-heart-fill","bi-calendar-minus","bi-calendar-minus-fill","bi-calendar-month","bi-calendar-month-fill","bi-calendar-plus","bi-calendar-plus-fill","bi-calendar-range","bi-calendar-range-fill","bi-calendar-week","bi-calendar-week-fill","bi-calendar-x","bi-calendar-x-fill","bi-calendar2","bi-calendar2-check","bi-calendar2-check-fill","bi-calendar2-date","bi-calendar2-date-fill","bi-calendar2-day","bi-calendar2-day-fill","bi-calendar2-event","bi-calendar2-event-fill","bi-calendar2-fill","bi-calendar2-heart","bi-calendar2-heart-fill","bi-calendar2-minus","bi-calendar2-minus-fill","bi-calendar2-month","bi-calendar2-month-fill","bi-calendar2-plus","bi-calendar2-plus-fill","bi-calendar2-range","bi-calendar2-range-fill","bi-calendar2-week","bi-calendar2-week-fill","bi-calendar2-x","bi-calendar2-x-fill","bi-calendar3","bi-calendar3-event","bi-calendar3-event-fill","bi-calendar3-fill","bi-calendar3-range","bi-calendar3-range-fill","bi-calendar3-week","bi-calendar3-week-fill","bi-calendar4","bi-calendar4-event","bi-calendar4-range","bi-calendar4-week","bi-camera","bi-camera2","bi-camera-fill","bi-camera-reels","bi-camera-reels-fill","bi-camera-video","bi-camera-video-fill","bi-camera-video-off","bi-camera-video-off-fill","bi-capslock","bi-capslock-fill","bi-capsule","bi-capsule-pill","bi-car-front","bi-car-front-fill","bi-card-checklist","bi-card-heading","bi-card-image","bi-card-list","bi-card-text","bi-caret-down","bi-caret-down-fill","bi-caret-down-square","bi-caret-down-square-fill","bi-caret-left","bi-caret-left-fill","bi-caret-left-square","bi-caret-left-square-fill","bi-caret-right","bi-caret-right-fill","bi-caret-right-square","bi-caret-right-square-fill","bi-caret-up","bi-caret-up-fill","bi-caret-up-square","bi-caret-up-square-fill","bi-cart","bi-cart-check","bi-cart-check-fill","bi-cart-dash","bi-cart-dash-fill","bi-cart-fill","bi-cart-plus","bi-cart-plus-fill","bi-cart-x","bi-cart-x-fill","bi-cart2","bi-cart3","bi-cart4","bi-cash","bi-cash-coin","bi-cash-stack","bi-cassette","bi-cassette-fill","bi-cast","bi-cc-circle","bi-cc-circle-fill","bi-cc-square","bi-cc-square-fill","bi-chat","bi-chat-dots","bi-chat-dots-fill","bi-chat-fill","bi-chat-heart","bi-chat-heart-fill","bi-chat-left","bi-chat-left-dots","bi-chat-left-dots-fill","bi-chat-left-fill","bi-chat-left-heart","bi-chat-left-heart-fill","bi-chat-left-quote","bi-chat-left-quote-fill","bi-chat-left-text","bi-chat-left-text-fill","bi-chat-quote","bi-chat-quote-fill","bi-chat-right","bi-chat-right-dots","bi-chat-right-dots-fill","bi-chat-right-fill","bi-chat-right-heart","bi-chat-right-heart-fill","bi-chat-right-quote","bi-chat-right-quote-fill","bi-chat-right-text","bi-chat-right-text-fill","bi-chat-square","bi-chat-square-dots","bi-chat-square-dots-fill","bi-chat-square-fill","bi-chat-square-heart","bi-chat-square-heart-fill","bi-chat-square-quote","bi-chat-square-quote-fill","bi-chat-square-text","bi-chat-square-text-fill","bi-chat-text","bi-chat-text-fill","bi-check","bi-check-all","bi-check-circle","bi-check-circle-fill","bi-check-lg","bi-check-square","bi-check-square-fill","bi-check2","bi-check2-all","bi-check2-circle","bi-check2-square","bi-chevron-bar-contract","bi-chevron-bar-down","bi-chevron-bar-expand","bi-chevron-bar-left","bi-chevron-bar-right","bi-chevron-bar-up","bi-chevron-compact-down","bi-chevron-compact-left","bi-chevron-compact-right","bi-chevron-compact-up","bi-chevron-contract","bi-chevron-double-down","bi-chevron-double-left","bi-chevron-double-right","bi-chevron-double-up","bi-chevron-down","bi-chevron-expand","bi-chevron-left","bi-chevron-right","bi-chevron-up","bi-circle","bi-circle-fill","bi-circle-half","bi-slash-circle","bi-circle-square","bi-clipboard","bi-clipboard-check","bi-clipboard-check-fill","bi-clipboard-data","bi-clipboard-data-fill","bi-clipboard-fill","bi-clipboard-heart","bi-clipboard-heart-fill","bi-clipboard-minus","bi-clipboard-minus-fill","bi-clipboard-plus","bi-clipboard-plus-fill","bi-clipboard-pulse","bi-clipboard-x","bi-clipboard-x-fill","bi-clipboard2","bi-clipboard2-check","bi-clipboard2-check-fill","bi-clipboard2-data","bi-clipboard2-data-fill","bi-clipboard2-fill","bi-clipboard2-heart","bi-clipboard2-heart-fill","bi-clipboard2-minus","bi-clipboard2-minus-fill","bi-clipboard2-plus","bi-clipboard2-plus-fill","bi-clipboard2-pulse","bi-clipboard2-pulse-fill","bi-clipboard2-x","bi-clipboard2-x-fill","bi-clock","bi-clock-fill","bi-clock-history","bi-cloud","bi-cloud-arrow-down","bi-cloud-arrow-down-fill","bi-cloud-arrow-up","bi-cloud-arrow-up-fill","bi-cloud-check","bi-cloud-check-fill","bi-cloud-download","bi-cloud-download-fill","bi-cloud-drizzle","bi-cloud-drizzle-fill","bi-cloud-fill","bi-cloud-fog","bi-cloud-fog-fill","bi-cloud-fog2","bi-cloud-fog2-fill","bi-cloud-hail","bi-cloud-hail-fill","bi-cloud-haze","bi-cloud-haze-fill","bi-cloud-haze2","bi-cloud-haze2-fill","bi-cloud-lightning","bi-cloud-lightning-fill","bi-cloud-lightning-rain","bi-cloud-lightning-rain-fill","bi-cloud-minus","bi-cloud-minus-fill","bi-cloud-moon","bi-cloud-moon-fill","bi-cloud-plus","bi-cloud-plus-fill","bi-cloud-rain","bi-cloud-rain-fill","bi-cloud-rain-heavy","bi-cloud-rain-heavy-fill","bi-cloud-slash","bi-cloud-slash-fill","bi-cloud-sleet","bi-cloud-sleet-fill","bi-cloud-snow","bi-cloud-snow-fill","bi-cloud-sun","bi-cloud-sun-fill","bi-cloud-upload","bi-cloud-upload-fill","bi-clouds","bi-clouds-fill","bi-cloudy","bi-cloudy-fill","bi-code","bi-code-slash","bi-code-square","bi-coin","bi-collection","bi-collection-fill","bi-collection-play","bi-collection-play-fill","bi-columns","bi-columns-gap","bi-command","bi-compass","bi-compass-fill","bi-cone","bi-cone-striped","bi-controller","bi-cpu","bi-cpu-fill","bi-credit-card","bi-credit-card-2-back","bi-credit-card-2-back-fill","bi-credit-card-2-front","bi-credit-card-2-front-fill","bi-credit-card-fill","bi-crop","bi-cup","bi-cup-fill","bi-cup-hot","bi-cup-hot-fill","bi-cup-straw","bi-currency-bitcoin","bi-currency-dollar","bi-currency-euro","bi-currency-exchange","bi-currency-pound","bi-currency-rupee","bi-currency-yen","bi-cursor","bi-cursor-fill","bi-cursor-text","bi-dash","bi-dash-circle","bi-dash-circle-dotted","bi-dash-circle-fill","bi-dash-lg","bi-dash-square","bi-dash-square-dotted","bi-dash-square-fill","bi-database","bi-database-add","bi-database-check","bi-database-dash","bi-database-down","bi-database-exclamation","bi-database-fill","bi-database-fill-add","bi-database-fill-check","bi-database-fill-dash","bi-database-fill-down","bi-database-fill-exclamation","bi-database-fill-gear","bi-database-fill-lock","bi-database-fill-slash","bi-database-fill-up","bi-database-fill-x","bi-database-gear","bi-database-lock","bi-database-slash","bi-database-up","bi-database-x","bi-device-hdd","bi-device-hdd-fill","bi-device-ssd","bi-device-ssd-fill","bi-diagram-2","bi-diagram-2-fill","bi-diagram-3","bi-diagram-3-fill","bi-diamond","bi-diamond-fill","bi-diamond-half","bi-dice-1","bi-dice-1-fill","bi-dice-2","bi-dice-2-fill","bi-dice-3","bi-dice-3-fill","bi-dice-4","bi-dice-4-fill","bi-dice-5","bi-dice-5-fill","bi-dice-6","bi-dice-6-fill","bi-disc","bi-disc-fill","bi-discord","bi-display","bi-display-fill","bi-displayport","bi-displayport-fill","bi-distribute-horizontal","bi-distribute-vertical","bi-door-closed","bi-door-closed-fill","bi-door-open","bi-door-open-fill","bi-dot","bi-download","bi-dpad","bi-dpad-fill","bi-dribbble","bi-dropbox","bi-droplet","bi-droplet-fill","bi-droplet-half","bi-ear","bi-ear-fill","bi-earbuds","bi-easel","bi-easel-fill","bi-easel2","bi-easel2-fill","bi-easel3","bi-easel3-fill","bi-egg","bi-egg-fill","bi-egg-fried","bi-eject","bi-eject-fill","bi-emoji-angry","bi-emoji-angry-fill","bi-emoji-dizzy","bi-emoji-dizzy-fill","bi-emoji-expressionless","bi-emoji-expressionless-fill","bi-emoji-frown","bi-emoji-frown-fill","bi-emoji-heart-eyes","bi-emoji-heart-eyes-fill","bi-emoji-kiss","bi-emoji-kiss-fill","bi-emoji-laughing","bi-emoji-laughing-fill","bi-emoji-neutral","bi-emoji-neutral-fill","bi-emoji-smile","bi-emoji-smile-fill","bi-emoji-smile-upside-down","bi-emoji-smile-upside-down-fill","bi-emoji-sunglasses","bi-emoji-sunglasses-fill","bi-emoji-wink","bi-emoji-wink-fill","bi-envelope","bi-envelope-at","bi-envelope-at-fill","bi-envelope-check","bi-envelope-check-fill","bi-envelope-dash","bi-envelope-dash-fill","bi-envelope-exclamation","bi-envelope-exclamation-fill","bi-envelope-fill","bi-envelope-heart","bi-envelope-heart-fill","bi-envelope-open","bi-envelope-open-fill","bi-envelope-open-heart","bi-envelope-open-heart-fill","bi-envelope-paper","bi-envelope-paper-fill","bi-envelope-paper-heart","bi-envelope-paper-heart-fill","bi-envelope-plus","bi-envelope-plus-fill","bi-envelope-slash","bi-envelope-slash-fill","bi-envelope-x","bi-envelope-x-fill","bi-eraser","bi-eraser-fill","bi-escape","bi-ethernet","bi-ev-front","bi-ev-front-fill","bi-ev-station","bi-ev-station-fill","bi-exclamation","bi-exclamation-circle","bi-exclamation-circle-fill","bi-exclamation-diamond","bi-exclamation-diamond-fill","bi-exclamation-lg","bi-exclamation-octagon","bi-exclamation-octagon-fill","bi-exclamation-square","bi-exclamation-square-fill","bi-exclamation-triangle","bi-exclamation-triangle-fill","bi-exclude","bi-explicit","bi-explicit-fill","bi-eye","bi-eye-fill","bi-eye-slash","bi-eye-slash-fill","bi-eyedropper","bi-eyeglasses","bi-facebook","bi-fan","bi-fast-forward","bi-fast-forward-btn","bi-fast-forward-btn-fill","bi-fast-forward-circle","bi-fast-forward-circle-fill","bi-fast-forward-fill","bi-file","bi-file-arrow-down","bi-file-arrow-down-fill","bi-file-arrow-up","bi-file-arrow-up-fill","bi-file-bar-graph","bi-file-bar-graph-fill","bi-file-binary","bi-file-binary-fill","bi-file-break","bi-file-break-fill","bi-file-check","bi-file-check-fill","bi-file-code","bi-file-code-fill","bi-file-diff","bi-file-diff-fill","bi-file-earmark","bi-file-earmark-arrow-down","bi-file-earmark-arrow-down-fill","bi-file-earmark-arrow-up","bi-file-earmark-arrow-up-fill","bi-file-earmark-bar-graph","bi-file-earmark-bar-graph-fill","bi-file-earmark-binary","bi-file-earmark-binary-fill","bi-file-earmark-break","bi-file-earmark-break-fill","bi-file-earmark-check","bi-file-earmark-check-fill","bi-file-earmark-code","bi-file-earmark-code-fill","bi-file-earmark-diff","bi-file-earmark-diff-fill","bi-file-earmark-easel","bi-file-earmark-easel-fill","bi-file-earmark-excel","bi-file-earmark-excel-fill","bi-file-earmark-fill","bi-file-earmark-font","bi-file-earmark-font-fill","bi-file-earmark-image","bi-file-earmark-image-fill","bi-file-earmark-lock","bi-file-earmark-lock-fill","bi-file-earmark-lock2","bi-file-earmark-lock2-fill","bi-file-earmark-medical","bi-file-earmark-medical-fill","bi-file-earmark-minus","bi-file-earmark-minus-fill","bi-file-earmark-music","bi-file-earmark-music-fill","bi-file-earmark-pdf","bi-file-earmark-pdf-fill","bi-file-earmark-person","bi-file-earmark-person-fill","bi-file-earmark-play","bi-file-earmark-play-fill","bi-file-earmark-plus","bi-file-earmark-plus-fill","bi-file-earmark-post","bi-file-earmark-post-fill","bi-file-earmark-ppt","bi-file-earmark-ppt-fill","bi-file-earmark-richtext","bi-file-earmark-richtext-fill","bi-file-earmark-ruled","bi-file-earmark-ruled-fill","bi-file-earmark-slides","bi-file-earmark-slides-fill","bi-file-earmark-spreadsheet","bi-file-earmark-spreadsheet-fill","bi-file-earmark-text","bi-file-earmark-text-fill","bi-file-earmark-word","bi-file-earmark-word-fill","bi-file-earmark-x","bi-file-earmark-x-fill","bi-file-earmark-zip","bi-file-earmark-zip-fill","bi-file-easel","bi-file-easel-fill","bi-file-excel","bi-file-excel-fill","bi-file-fill","bi-file-font","bi-file-font-fill","bi-file-image","bi-file-image-fill","bi-file-lock","bi-file-lock-fill","bi-file-lock2","bi-file-lock2-fill","bi-file-medical","bi-file-medical-fill","bi-file-minus","bi-file-minus-fill","bi-file-music","bi-file-music-fill","bi-file-pdf","bi-file-pdf-fill","bi-file-person","bi-file-person-fill","bi-file-play","bi-file-play-fill","bi-file-plus","bi-file-plus-fill","bi-file-post","bi-file-post-fill","bi-file-ppt","bi-file-ppt-fill","bi-file-richtext","bi-file-richtext-fill","bi-file-ruled","bi-file-ruled-fill","bi-file-slides","bi-file-slides-fill","bi-file-spreadsheet","bi-file-spreadsheet-fill","bi-file-text","bi-file-text-fill","bi-file-word","bi-file-word-fill","bi-file-x","bi-file-x-fill","bi-file-zip","bi-file-zip-fill","bi-files","bi-files-alt","bi-filetype-aac","bi-filetype-ai","bi-filetype-bmp","bi-filetype-cs","bi-filetype-css","bi-filetype-csv","bi-filetype-doc","bi-filetype-docx","bi-filetype-exe","bi-filetype-gif","bi-filetype-heic","bi-filetype-html","bi-filetype-java","bi-filetype-jpg","bi-filetype-js","bi-filetype-json","bi-filetype-jsx","bi-filetype-key","bi-filetype-m4p","bi-filetype-md","bi-filetype-mdx","bi-filetype-mov","bi-filetype-mp3","bi-filetype-mp4","bi-filetype-otf","bi-filetype-pdf","bi-filetype-php","bi-filetype-png","bi-filetype-ppt","bi-filetype-pptx","bi-filetype-psd","bi-filetype-py","bi-filetype-raw","bi-filetype-rb","bi-filetype-sass","bi-filetype-scss","bi-filetype-sh","bi-filetype-sql","bi-filetype-svg","bi-filetype-tiff","bi-filetype-tsx","bi-filetype-ttf","bi-filetype-txt","bi-filetype-wav","bi-filetype-woff","bi-filetype-xls","bi-filetype-xlsx","bi-filetype-xml","bi-filetype-yml","bi-film","bi-filter","bi-filter-circle","bi-filter-circle-fill","bi-filter-left","bi-filter-right","bi-filter-square","bi-filter-square-fill","bi-fingerprint","bi-fire","bi-flag","bi-flag-fill","bi-flower1","bi-flower2","bi-flower3","bi-folder","bi-folder-check","bi-folder-fill","bi-folder-minus","bi-folder-plus","bi-folder-symlink","bi-folder-symlink-fill","bi-folder-x","bi-folder2","bi-folder2-open","bi-fonts","bi-forward","bi-forward-fill","bi-front","bi-fuel-pump","bi-fuel-pump-diesel","bi-fuel-pump-diesel-fill","bi-fuel-pump-fill","bi-fullscreen","bi-fullscreen-exit","bi-funnel","bi-funnel-fill","bi-gear","bi-gear-fill","bi-gear-wide","bi-gear-wide-connected","bi-gem","bi-gender-ambiguous","bi-gender-female","bi-gender-male","bi-gender-trans","bi-geo","bi-geo-alt","bi-geo-alt-fill","bi-geo-fill","bi-gift","bi-gift-fill","bi-git","bi-github","bi-globe","bi-globe-americas","bi-globe-asia-australia","bi-globe-central-south-asia","bi-globe-europe-africa","bi-globe2","bi-google","bi-google-play","bi-gpu-card","bi-graph-down","bi-graph-down-arrow","bi-graph-up","bi-graph-up-arrow","bi-grid","bi-grid-1x2","bi-grid-1x2-fill","bi-grid-3x2","bi-grid-3x2-gap","bi-grid-3x2-gap-fill","bi-grid-3x3","bi-grid-3x3-gap","bi-grid-3x3-gap-fill","bi-grid-fill","bi-grip-horizontal","bi-grip-vertical","bi-h-circle","bi-h-circle-fill","bi-h-square","bi-h-square-fill","bi-hammer","bi-hand-index","bi-hand-index-fill","bi-hand-index-thumb","bi-hand-index-thumb-fill","bi-hand-thumbs-down","bi-hand-thumbs-down-fill","bi-hand-thumbs-up","bi-hand-thumbs-up-fill","bi-handbag","bi-handbag-fill","bi-hash","bi-hdd","bi-hdd-fill","bi-hdd-network","bi-hdd-network-fill","bi-hdd-rack","bi-hdd-rack-fill","bi-hdd-stack","bi-hdd-stack-fill","bi-hdmi","bi-hdmi-fill","bi-headphones","bi-headset","bi-headset-vr","bi-heart","bi-heart-arrow","bi-heart-fill","bi-heart-half","bi-heart-pulse","bi-heart-pulse-fill","bi-heartbreak","bi-heartbreak-fill","bi-hearts","bi-heptagon","bi-heptagon-fill","bi-heptagon-half","bi-hexagon","bi-hexagon-fill","bi-hexagon-half","bi-hospital","bi-hospital-fill","bi-hourglass","bi-hourglass-bottom","bi-hourglass-split","bi-hourglass-top","bi-house","bi-house-add","bi-house-add-fill","bi-house-check","bi-house-check-fill","bi-house-dash","bi-house-dash-fill","bi-house-door","bi-house-door-fill","bi-house-down","bi-house-down-fill","bi-house-exclamation","bi-house-exclamation-fill","bi-house-fill","bi-house-gear","bi-house-gear-fill","bi-house-heart","bi-house-heart-fill","bi-house-lock","bi-house-lock-fill","bi-house-slash","bi-house-slash-fill","bi-house-up","bi-house-up-fill","bi-house-x","bi-house-x-fill","bi-houses","bi-houses-fill","bi-hr","bi-hurricane","bi-hypnotize","bi-image","bi-image-alt","bi-image-fill","bi-images","bi-inbox","bi-inbox-fill","bi-inboxes-fill","bi-inboxes","bi-incognito","bi-indent","bi-infinity","bi-info","bi-info-circle","bi-info-circle-fill","bi-info-lg","bi-info-square","bi-info-square-fill","bi-input-cursor","bi-input-cursor-text","bi-instagram","bi-intersect","bi-journal","bi-journal-album","bi-journal-arrow-down","bi-journal-arrow-up","bi-journal-bookmark","bi-journal-bookmark-fill","bi-journal-check","bi-journal-code","bi-journal-medical","bi-journal-minus","bi-journal-plus","bi-journal-richtext","bi-journal-text","bi-journal-x","bi-journals","bi-joystick","bi-justify","bi-justify-left","bi-justify-right","bi-kanban","bi-kanban-fill","bi-key","bi-key-fill","bi-keyboard","bi-keyboard-fill","bi-ladder","bi-lamp","bi-lamp-fill","bi-laptop","bi-laptop-fill","bi-layer-backward","bi-layer-forward","bi-layers","bi-layers-fill","bi-layers-half","bi-layout-sidebar","bi-layout-sidebar-inset-reverse","bi-layout-sidebar-inset","bi-layout-sidebar-reverse","bi-layout-split","bi-layout-text-sidebar","bi-layout-text-sidebar-reverse","bi-layout-text-window","bi-layout-text-window-reverse","bi-layout-three-columns","bi-layout-wtf","bi-life-preserver","bi-lightbulb","bi-lightbulb-fill","bi-lightbulb-off","bi-lightbulb-off-fill","bi-lightning","bi-lightning-charge","bi-lightning-charge-fill","bi-lightning-fill","bi-line","bi-link","bi-link-45deg","bi-linkedin","bi-list","bi-list-check","bi-list-columns","bi-list-columns-reverse","bi-list-nested","bi-list-ol","bi-list-stars","bi-list-task","bi-list-ul","bi-lock","bi-lock-fill","bi-lungs","bi-lungs-fill","bi-magic","bi-magnet","bi-magnet-fill","bi-mailbox","bi-mailbox2","bi-map","bi-map-fill","bi-markdown","bi-markdown-fill","bi-mask","bi-mastodon","bi-medium","bi-megaphone","bi-megaphone-fill","bi-memory","bi-menu-app","bi-menu-app-fill","bi-menu-button","bi-menu-button-fill","bi-menu-button-wide","bi-menu-button-wide-fill","bi-menu-down","bi-menu-up","bi-messenger","bi-meta","bi-mic","bi-mic-fill","bi-mic-mute","bi-mic-mute-fill","bi-microsoft","bi-microsoft-teams","bi-minecart","bi-minecart-loaded","bi-modem","bi-modem-fill","bi-moisture","bi-moon","bi-moon-fill","bi-moon-stars","bi-moon-stars-fill","bi-mortarboard","bi-mortarboard-fill","bi-motherboard","bi-motherboard-fill","bi-mouse","bi-mouse-fill","bi-mouse2","bi-mouse2-fill","bi-mouse3","bi-mouse3-fill","bi-music-note","bi-music-note-beamed","bi-music-note-list","bi-music-player","bi-music-player-fill","bi-newspaper","bi-nintendo-switch","bi-node-minus","bi-node-minus-fill","bi-node-plus","bi-node-plus-fill","bi-nut","bi-nut-fill","bi-nvidia","bi-octagon","bi-octagon-fill","bi-octagon-half","bi-optical-audio","bi-optical-audio-fill","bi-option","bi-outlet","bi-p-circle","bi-p-circle-fill","bi-p-square","bi-p-square-fill","bi-paint-bucket","bi-palette","bi-palette-fill","bi-palette2","bi-paperclip","bi-paragraph","bi-pass","bi-pass-fill","bi-patch-check","bi-patch-check-fill","bi-patch-exclamation","bi-patch-exclamation-fill","bi-patch-minus","bi-patch-minus-fill","bi-patch-plus","bi-patch-plus-fill","bi-patch-question","bi-patch-question-fill","bi-pause","bi-pause-btn","bi-pause-btn-fill","bi-pause-circle","bi-pause-circle-fill","bi-pause-fill","bi-paypal","bi-pc","bi-pc-display","bi-pc-display-horizontal","bi-pc-horizontal","bi-pci-card","bi-peace","bi-peace-fill","bi-pen","bi-pen-fill","bi-pencil","bi-pencil-fill","bi-pencil-square","bi-pentagon","bi-pentagon-fill","bi-pentagon-half","bi-people","bi-person-circle","bi-people-fill","bi-percent","bi-person","bi-person-add","bi-person-badge","bi-person-badge-fill","bi-person-bounding-box","bi-person-check","bi-person-check-fill","bi-person-dash","bi-person-dash-fill","bi-person-down","bi-person-exclamation","bi-person-fill","bi-person-fill-add","bi-person-fill-check","bi-person-fill-dash","bi-person-fill-down","bi-person-fill-exclamation","bi-person-fill-gear","bi-person-fill-lock","bi-person-fill-slash","bi-person-fill-up","bi-person-fill-x","bi-person-gear","bi-person-heart","bi-person-hearts","bi-person-lines-fill","bi-person-lock","bi-person-plus","bi-person-plus-fill","bi-person-rolodex","bi-person-slash","bi-person-square","bi-person-up","bi-person-vcard","bi-person-vcard-fill","bi-person-video","bi-person-video2","bi-person-video3","bi-person-workspace","bi-person-x","bi-person-x-fill","bi-phone","bi-phone-fill","bi-phone-flip","bi-phone-landscape","bi-phone-landscape-fill","bi-phone-vibrate","bi-phone-vibrate-fill","bi-pie-chart","bi-pie-chart-fill","bi-piggy-bank","bi-piggy-bank-fill","bi-pin","bi-pin-angle","bi-pin-angle-fill","bi-pin-fill","bi-pin-map","bi-pin-map-fill","bi-pinterest","bi-pip","bi-pip-fill","bi-play","bi-play-btn","bi-play-btn-fill","bi-play-circle","bi-play-circle-fill","bi-play-fill","bi-playstation","bi-plug","bi-plug-fill","bi-plugin","bi-plus","bi-plus-circle","bi-plus-circle-dotted","bi-plus-circle-fill","bi-plus-lg","bi-plus-slash-minus","bi-plus-square","bi-plus-square-dotted","bi-plus-square-fill","bi-postage","bi-postage-fill","bi-postage-heart","bi-postage-heart-fill","bi-postcard","bi-postcard-fill","bi-postcard-heart","bi-postcard-heart-fill","bi-power","bi-prescription","bi-prescription2","bi-printer","bi-printer-fill","bi-projector","bi-projector-fill","bi-puzzle","bi-puzzle-fill","bi-qr-code","bi-qr-code-scan","bi-question","bi-question-circle","bi-question-diamond","bi-question-diamond-fill","bi-question-circle-fill","bi-question-lg","bi-question-octagon","bi-question-octagon-fill","bi-question-square","bi-question-square-fill","bi-quora","bi-quote","bi-r-circle","bi-r-circle-fill","bi-r-square","bi-r-square-fill","bi-radioactive","bi-rainbow","bi-receipt","bi-receipt-cutoff","bi-reception-0","bi-reception-1","bi-reception-2","bi-reception-3","bi-reception-4","bi-record","bi-record-btn","bi-record-btn-fill","bi-record-circle","bi-record-circle-fill","bi-record-fill","bi-record2","bi-record2-fill","bi-recycle","bi-reddit","bi-regex","bi-repeat","bi-repeat-1","bi-reply","bi-reply-all","bi-reply-all-fill","bi-reply-fill","bi-rewind","bi-rewind-btn","bi-rewind-btn-fill","bi-rewind-circle","bi-rewind-circle-fill","bi-rewind-fill","bi-robot","bi-rocket","bi-rocket-fill","bi-rocket-takeoff","bi-rocket-takeoff-fill","bi-router","bi-router-fill","bi-rss","bi-rss-fill","bi-rulers","bi-safe","bi-safe-fill","bi-safe2","bi-safe2-fill","bi-save","bi-save-fill","bi-save2","bi-save2-fill","bi-scissors","bi-scooter","bi-screwdriver","bi-sd-card","bi-sd-card-fill","bi-search","bi-search-heart","bi-search-heart-fill","bi-segmented-nav","bi-send","bi-send-check","bi-send-check-fill","bi-send-dash","bi-send-dash-fill","bi-send-exclamation","bi-send-exclamation-fill","bi-send-fill","bi-send-plus","bi-send-plus-fill","bi-send-slash","bi-send-slash-fill","bi-send-x","bi-send-x-fill","bi-server","bi-share","bi-share-fill","bi-shield","bi-shield-check","bi-shield-exclamation","bi-shield-fill","bi-shield-fill-check","bi-shield-fill-exclamation","bi-shield-fill-minus","bi-shield-fill-plus","bi-shield-fill-x","bi-shield-lock","bi-shield-lock-fill","bi-shield-minus","bi-shield-plus","bi-shield-shaded","bi-shield-slash","bi-shield-slash-fill","bi-shield-x","bi-shift","bi-shift-fill","bi-shop","bi-shop-window","bi-shuffle","bi-sign-dead-end","bi-sign-dead-end-fill","bi-sign-do-not-enter","bi-sign-do-not-enter-fill","bi-sign-intersection","bi-sign-intersection-fill","bi-sign-intersection-side","bi-sign-intersection-side-fill","bi-sign-intersection-t","bi-sign-intersection-t-fill","bi-sign-intersection-y","bi-sign-intersection-y-fill","bi-sign-merge-left","bi-sign-merge-left-fill","bi-sign-merge-right","bi-sign-merge-right-fill","bi-sign-no-left-turn","bi-sign-no-left-turn-fill","bi-sign-no-parking","bi-sign-no-parking-fill","bi-sign-no-right-turn","bi-sign-no-right-turn-fill","bi-sign-railroad","bi-sign-railroad-fill","bi-sign-stop","bi-sign-stop-fill","bi-sign-stop-lights","bi-sign-stop-lights-fill","bi-sign-turn-left","bi-sign-turn-left-fill","bi-sign-turn-right","bi-sign-turn-right-fill","bi-sign-turn-slight-left","bi-sign-turn-slight-left-fill","bi-sign-turn-slight-right","bi-sign-turn-slight-right-fill","bi-sign-yield","bi-sign-yield-fill","bi-signal","bi-signpost","bi-signpost-2","bi-signpost-2-fill","bi-signpost-fill","bi-signpost-split","bi-signpost-split-fill","bi-sim","bi-sim-fill","bi-sina-weibo","bi-skip-backward","bi-skip-backward-btn","bi-skip-backward-btn-fill","bi-skip-backward-circle","bi-skip-backward-circle-fill","bi-skip-backward-fill","bi-skip-end","bi-skip-end-btn","bi-skip-end-btn-fill","bi-skip-end-circle","bi-skip-end-circle-fill","bi-skip-end-fill","bi-skip-forward","bi-skip-forward-btn","bi-skip-forward-btn-fill","bi-skip-forward-circle","bi-skip-forward-circle-fill","bi-skip-forward-fill","bi-skip-start","bi-skip-start-btn","bi-skip-start-btn-fill","bi-skip-start-circle","bi-skip-start-circle-fill","bi-skip-start-fill","bi-skype","bi-slack","bi-slash","bi-slash-circle-fill","bi-slash-lg","bi-slash-square","bi-slash-square-fill","bi-sliders","bi-sliders2","bi-sliders2-vertical","bi-smartwatch","bi-snapchat","bi-snow","bi-snow2","bi-snow3","bi-sort-alpha-down","bi-sort-alpha-down-alt","bi-sort-alpha-up","bi-sort-alpha-up-alt","bi-sort-down","bi-sort-down-alt","bi-sort-numeric-down","bi-sort-numeric-down-alt","bi-sort-numeric-up","bi-sort-numeric-up-alt","bi-sort-up","bi-sort-up-alt","bi-soundwave","bi-speaker","bi-speaker-fill","bi-speedometer","bi-speedometer2","bi-spellcheck","bi-spotify","bi-square","bi-square-fill","bi-square-half","bi-stack","bi-stack-overflow","bi-star","bi-star-fill","bi-star-half","bi-stars","bi-steam","bi-stickies","bi-stickies-fill","bi-sticky","bi-sticky-fill","bi-stop","bi-stop-btn","bi-stop-btn-fill","bi-stop-circle","bi-stop-circle-fill","bi-stop-fill","bi-stoplights","bi-stoplights-fill","bi-stopwatch","bi-stopwatch-fill","bi-strava","bi-stripe","bi-subscript","bi-subtract","bi-suit-club","bi-suit-club-fill","bi-suit-diamond","bi-suit-diamond-fill","bi-suit-heart","bi-suit-heart-fill","bi-suit-spade","bi-suit-spade-fill","bi-sun","bi-sun-fill","bi-sunglasses","bi-sunrise","bi-sunrise-fill","bi-sunset","bi-sunset-fill","bi-superscript","bi-symmetry-horizontal","bi-symmetry-vertical","bi-table","bi-tablet","bi-tablet-fill","bi-tablet-landscape","bi-tablet-landscape-fill","bi-tag","bi-tag-fill","bi-tags","bi-tags-fill","bi-taxi-front","bi-taxi-front-fill","bi-telegram","bi-telephone","bi-telephone-fill","bi-telephone-forward","bi-telephone-forward-fill","bi-telephone-inbound","bi-telephone-inbound-fill","bi-telephone-minus","bi-telephone-minus-fill","bi-telephone-outbound","bi-telephone-outbound-fill","bi-telephone-plus","bi-telephone-plus-fill","bi-telephone-x","bi-telephone-x-fill","bi-tencent-qq","bi-terminal","bi-terminal-dash","bi-terminal-fill","bi-terminal-plus","bi-terminal-split","bi-terminal-x","bi-text-center","bi-text-indent-left","bi-text-indent-right","bi-text-left","bi-text-paragraph","bi-text-right","bi-text-wrap","bi-textarea","bi-textarea-resize","bi-textarea-t","bi-thermometer","bi-thermometer-half","bi-thermometer-high","bi-thermometer-low","bi-thermometer-snow","bi-thermometer-sun","bi-three-dots","bi-three-dots-vertical","bi-thunderbolt","bi-thunderbolt-fill","bi-ticket","bi-ticket-detailed","bi-ticket-detailed-fill","bi-ticket-fill","bi-ticket-perforated","bi-ticket-perforated-fill","bi-tiktok","bi-toggle-off","bi-toggle-on","bi-toggle2-off","bi-toggle2-on","bi-toggles","bi-toggles2","bi-tools","bi-tornado","bi-train-freight-front","bi-train-freight-front-fill","bi-train-front","bi-train-front-fill","bi-train-lightrail-front","bi-train-lightrail-front-fill","bi-translate","bi-trash","bi-trash-fill","bi-trash2","bi-trash2-fill","bi-trash3","bi-trash3-fill","bi-tree","bi-tree-fill","bi-trello","bi-triangle","bi-triangle-fill","bi-triangle-half","bi-trophy","bi-trophy-fill","bi-tropical-storm","bi-truck","bi-truck-flatbed","bi-truck-front","bi-truck-front-fill","bi-tsunami","bi-tv","bi-tv-fill","bi-twitch","bi-twitter","bi-type","bi-type-bold","bi-type-h1","bi-type-h2","bi-type-h3","bi-type-italic","bi-type-strikethrough","bi-type-underline","bi-ubuntu","bi-ui-checks","bi-ui-checks-grid","bi-ui-radios","bi-ui-radios-grid","bi-umbrella","bi-umbrella-fill","bi-unindent","bi-union","bi-unity","bi-universal-access","bi-universal-access-circle","bi-unlock","bi-unlock-fill","bi-upc","bi-upc-scan","bi-upload","bi-usb","bi-usb-c","bi-usb-c-fill","bi-usb-drive","bi-usb-drive-fill","bi-usb-fill","bi-usb-micro","bi-usb-micro-fill","bi-usb-mini","bi-usb-mini-fill","bi-usb-plug","bi-usb-plug-fill","bi-usb-symbol","bi-valentine","bi-valentine2","bi-vector-pen","bi-view-list","bi-view-stacked","bi-vimeo","bi-vinyl","bi-vinyl-fill","bi-virus","bi-virus2","bi-voicemail","bi-volume-down","bi-volume-down-fill","bi-volume-mute","bi-volume-mute-fill","bi-volume-off","bi-volume-off-fill","bi-volume-up","bi-volume-up-fill","bi-vr","bi-wallet","bi-wallet-fill","bi-wallet2","bi-watch","bi-water","bi-webcam","bi-webcam-fill","bi-wechat","bi-whatsapp","bi-wifi","bi-wifi-1","bi-wifi-2","bi-wifi-off","bi-wikipedia","bi-wind","bi-window","bi-window-dash","bi-window-desktop","bi-window-dock","bi-window-fullscreen","bi-window-plus","bi-window-sidebar","bi-window-split","bi-window-stack","bi-window-x","bi-windows","bi-wordpress","bi-wrench","bi-wrench-adjustable","bi-wrench-adjustable-circle","bi-wrench-adjustable-circle-fill","bi-x","bi-x-circle","bi-x-circle-fill","bi-x-diamond","bi-x-diamond-fill","bi-x-lg","bi-x-octagon","bi-x-octagon-fill","bi-x-square","bi-x-square-fill","bi-xbox","bi-yelp","bi-yin-yang","bi-youtube","bi-zoom-in","bi-zoom-out"
      ],
    };
  },
};
</script>


<style lang="less" scoped>
.icons-item {
  float: left;
  margin: 6px 6px 6px 0;
  width: 115px;
  text-align: center;
  list-style: none;
  cursor: pointer;
  height: 100px;
  color: #5c6b77;
  transition: all 0.2s ease;
  position: relative;
  padding-top: 10px;
}
.active {
  border: 1px solid;
  background: #f44336;
  color: white;
  font-size: 32px;
}
</style>
