export default {
    "审批流程":"workflow",
    "基础设置":"settings",
    "基础组件":"components",
    "框架文档":"doc",
    "仓库管理":"Warehouse",
    "设备管理":"Equipment",
    "最多只能选[5]张图片": "You can only select [5] pictures at most",
    "最多只能选[5]个文件": "Only [5] files can be selected at most",
    "只能选择excel文件": "Only Excel files can be selected",
    "文件大小不能超过": "The file size cannot exceed",
    "最多可输入[{$ts}]个字符": "a maximum of [{$ts}] characters can be entered",
    "第[{$ts}]行,[{$ts}]验证未通过": "Line [{$ts},{$ts}] failed verificatio",
    "删除成功,共[{$ts}]条数据": "Deletion succeeded, with a total of [{$ts}] data",
    "[{$ts}]不能为空": "[{$ts}] is required",
    "[{$ts},{$ts}]不能为空": "[{$ts},{$ts}] is required",
    "无数据": "No data",
    "[{$ts}]重复": "[{$ts}] repeated",
    "搜索": "Search",
    "详情": "Details",
    "重复": "repeated",
    "重复记录": "Repeated recording",
    "重置": "Reset",
    "重置筛选条件": "Reset filter",
    "角色管理": "Role info",
    "角色名称": "Role",
    "角色": "Role",
    "设置": "Setting",
    "保存筛选条件": "Save filter",
    "保存成功,共{$ts}条数据": "Saved successfully, {$ts} item in total",
    "选择": "Select",
    "选择文件": "Select file",
    "请选择行": "Please select rows",
    "修改人": "Modifier",
    "修改密码": "Password",
    "修改时间": "Modify time",
    "模块": "Module",
    "月": "Months",
    "更多": "More",
    "名字": "Name",
    "邮箱": "Mail",
    "女": "Male",
    "男": "Ma",
    "菜单": "Menu",
    "菜单名称": "Menu name",
    "菜单设置": "Menu",
    "提示": "Message",
    "否": "No",
    "父级ID": "Parent ID",
    "上级角色": "Parent role",
    "密码": "Password",
    "权限": "Permissio",
    "个人中心": "Personal Center",
    "请输入": "Please input",
    "请选择": "Please select",
    "请选择文件": "Please select file",
    "其他": "Other",
    "必须是数字": "not a number",
    "备注": "Notes",
    "确认": "OK",
    "是": "Yes",
    "不存在": "does not exist",
    "系统": "System",
    "表名": "Table Name",
    "电话": "Tel",
    "时间": "Time",
    "排序号": "Sort NO",
    "状态": "Status",
    "操作成功": "Success",
    "删除成功": "Successfully Delete",
    "保存成功": "Successfully save",
    "摘要": "Summary",
    "超级管理员": "Super Admi",
    "确定": "Confirm",
    "用户管理": "User info",
    "用户名": "Account",
    "用户权限": "User permission",
    "用户基础信息": "User info",
    "用户名或密码错误": "Account or password incorrect",
    "值": "Value",
    "查看": "View",
    "警告": "Warning",
    "最多{$ts}个字符": "Up to {$ts} characters",
    "上传文件": "Upload",
    "上传": "Upload",
    "文件上传成功": "Upload succeeded",
    "代码生成": "Coder",
    "公司名称": "Company",
    "公司地址": "Company address",
    "公司管理": "Company info",
    "所属公司": "Company name",
    "公司类别": "Company type",
    "保存后继续添加": "Continue adding after saving",
    "成本": "Cost",
    "国家": "Country",
    "国家代码": "CountryCode",
    "创建时间": "Create time",
    "创建人": "Creator",
    "验证码": "code",
    "关闭": "Close",
    "只能是日期格式": "Can only be in date format",
    "取消": "Cancel",
    "不能大于": "cannot be greater tha",
    "不能小于": "cannot be less tha",
    "选中checkbox隐藏/显示列数据": "Select check box to hide / show column data",
    "中国": "China",
    "中文": "Chinese",
    "描述": "Descriptio",
    "数据字典": "Dictionary",
    "字典名称": "Dictionary Name",
    "字典编号": "Dictionary Number",
    "完成": "Done",
    "字典数据": "Data Source",
    "数据源": "Data Source",
    "下拉框绑定设置": "Data source",
    "日期": "Date",
    "删除": "Delete",
    "天": "Days",
    "帐号": "Account",
    "操作类型": "Action type",
    "新建": "Add",
    "添加子级": "Add a subset",
    "添加备注": "Add note",
    "添加行": "Add Row",
    "添加同级": "Add Siblings",
    "地址": "Address",
    "全选": "All",
    "不能为空": "is required",
    "参数设置": "Parameters",
    "真实姓名": "Real Name",
    "【{$ts}】不是模板中的列": "【{$ts}】 is not a column in the template",
    "第[{$ts}]行,[{$ts}]验证未通过,必须是日期格式": "Line [{$ts},{$ts}] validation failed, must be in date format",
    "第[{$ts}]行,[{$ts}]验证未通过,不能为空": "Line [{$ts},{$ts}] failed verification, cannot be empty",
    "[{$ts}]数据字典缺失": "[{$ts}] no data source is configured",
    "第[{$ts}]行,[{$ts}]验证未通过,只能输入": "Line [{$ts},{$ts}] failed verification, only input",
    "账号登录": "Login account",
    "正在登陆": "Logging",
    "登录": "Login",
    "登陆成功": "Login Succeeded",
    "语言设置": "Language",
    "系统设置": "System",
    "日志管理": "Logger",
    "英文": "English",
    "德语": "Deutsch",
    "印尼语": "Indonesia",
    "语言包": "Package",
    "权限管理": "Permission",
    "其他权限": "Other",
    "菜单列表": "Menu list",
    "确认要删除选择的数据吗?": "Are you sure you want to delete the selected data?",
    "正在处理": "Processing",
    "查询": "Search",
    "编辑": "Edit",
    "生成语言包": "Create package",
    "导入": "Import",
    "导出": "Export",
    "新增": "Add",
    "请输入正确的手机号": "Please input the correct mobile phone number",
    "密码长度不能小于6位": "The password length cannot be less than 6 digits",
    "只能是整数": "required is an integer",
    "只能是数字": "required are numbers",
    "必须是一个邮箱地址": "It must be an email address",
    "是否启用": "Enable",
    "sql语句": "Sql",
    "旧密码不能为空": "Old password cannot be empty\\r\\n",
    "新密码不能为空": "New password cannot be empty",
    "旧密码不正确": "The old password is incorrect",
    "新密码不能与旧密码相同": "The new password cannot be the same as the old password",
    "密码修改成功\\r\\n": "Password modified successfully",
    "不能选择此角色": "This role cannot be selected",
    "用户名已经被注册\\r\\n": "The user name has been registered",
    "用户新建成功.帐号[{$ts}],密码[{$ts}]": "User created successfully. Account number [{$ts}], password [{$ts}]",
    "没有权限": "No permission",
    "不能修改自己的角色": "You cannot modify your own role",
    "角色名【{$ts}】已存在": "Role name [{$ts}] already exists\\r\\n",
    "上级角色不能选择自己": "Superior roles cannot choose themselves",
    "不能选择此上级角色，选择的上级角色与当前角色形成依赖关系": "This superior role cannot be selected. The selected superior role is dependent on the current role",
    "服务器处理出现异常": "Server processing exceptio",
    "未找到上传的文件": "Upload file not found",
    "[{$ts}]不是模板中的列": "[{$ts}] is not a column in the template",
    "[{$ts}]列名重复": "Duplicate column name [{$ts}]",
    "导入文件列必须与导入模板相同": "The import file columns must be the same as the import template",
    "下载模板": "Download template",
    "上传结果": "Import result",
    "保存": "Save",
    "请上传文件": "Please upload the file",
    "上传失败": "Upload failed",
    "皮肤": "Theme",
    "框架文档": "Document",
    "安全退出": "Log out",
    "首页": "Home",
    "角色ID": "Role ID",
    "部门名称": "Department",
    "删除行": "Delete row",
    "刷新": "Refresh",
    "字典明细": "Dictionary details",
    "是否可用": "Enable",
    "数据源Text": "Text",
    "数据源Value": "Value",
    "数据源ID": "ID",
    "系统日志": "Logger",
    "开始时间": "Start time",
    "用户名称": "Name",
    "请求地址": "Url",
    "日志类型": "Log type",
    "响应状态": "Status",
    "时长": "Duratio",
    "请求参数": "Request",
    "响应参数": "Response",
    "异常信息": "Exception",
    "用户IP": "User IP",
    "浏览器类型": "Browser",
    "性别": "Gender",
    "操作": "Actio",
    "头像": "Header",
    "注册时间": "Reg time",
    "审核": "Audit",
    "视图/表名": "Table/View",
    "菜单ID": "Menu ID",
    "用户信息": "User info",
    "验证码不正确": "Incorrect verification code",
    "手机用户": "Mobile users",
    "语言管理": "Language",
    "简体中文": "zh-cn",
    "繁体中文": "zh-tw",
    "英语": "English",
    "法语": "French",
    "西班牙语": "Spanish",
    "俄语": "Russian",
    "高级查询": "Query",
    "角色列表": "Role list",
    "姓名": "Name",
    "阿拉伯语": "Arabic",
    "只能上传excel文件,文件大小不超过5M": "Only Excel files can be uploaded, and the file size shall not exceed 5m",
    "选择的文件【{$ts}】只能是excel文件": "The selected file [{$ts}] can only be an excel file",
    "选择的文件【{$ts}】只能是图片格式": "The selected file [{$ts}] can only be in picture format",
    "最多只能选【{$ts}】张图片": "You can only select [{$ts}] pictures at most",
    "最多只能选【{$ts}】个文件": "You can only select [{$ts}] files at most",
    "不支持此文件格式": "This file format is not supported",
    "文件不能超过[{$ts}]m": "File cannot exceed [{$ts}] m",
    "上传中": "Uploading",
    "文件列表": "File list",
    "文件名": "Filen name",
    "大小": "Size",
    "未能处理导入的文件,请检查导入的文件是否正确": "Failed to process the imported file. Please check whether the imported file is correct",
    "Token已过期": "The token has expired",
    "密码长度不能少于6位": "Password length cannot be less than 6",
    "密码修改成功": "Password modified successfully",
    "用户不存在": "user does not exist",
    "当前菜单存在子菜单,请先删除子菜单": "There are sub menus in the current menu. Please delete the sub menu first",
    "【字典项名称】不能有重复的值": "[dictionary item name] cannot have duplicate values",
    "【字典项Key】不能有重复的值": "[dictionary key] cannot have duplicate values",
    "字典编号[{$ts}]已存在": "Dictionary number [{$ts}] already exists\\n\\n",
    "账号": "account",
    "越南语": "Vietnamese",
    "泰语": "Thai",
    "结束时间": "End time",
    "是否显示": "Show or not",
    "列名": "Field",
    "拖动列名可调整表格列显示顺序": "Drag column names to adjust the display order of table columns",
    "集团租户": "Group",
    "组织构架": "Organizational",
    "集团管理": "Group",
    "数据分库": "Database",
    "演示菜单": "Example",
    "表单设计": "Form Design",
    "流程管理": "Workflow",
    "一对多生成": "Multiple Tables",
    "新窗口编辑": "New Tab",
    "打印设计": "Print",
    "消息推送": "Message",
    "定时任务": "Tasks",
    "名称": "Name",
    "编号": "Code",
    "类型": "Type",
    "集团名称": "Group name",
    "大屏数据": "Data",
    "MES业务": "MES",
    "工作台设计器": "Workbench Designer",
    "数据验证未通过!": "Data validation failed!",
    "开发文档": "Document",
    "外部链接": "Link",
    "窗口编辑": "Window Edit",
    "报表管理": "Report",
    "单据编码": "Document code",
    "工作台": "Workstation",
    "租户分库": "Tenant Management",
    "组件示例": "Component Example",
    "组件扩展": "Component extension",
    "已签收": "已签收-01",
    "业务系统": "Business system",
    "系统管理": "System management"
}