
export const columnType = [
  { key: 1, value: "img(图片)" },
  { key: 2, value: "excel" },
  { key: 3, value: "file(文件)" },
  { key: 6, value: "year(年)" },
  { key: 4, value: "date(年月日)" },
  { key: 5, value: "month(年月)" },
];

export const dataType = [
  { key: "text", value: "输入框" },
  { key: "select", value: "下拉框", requireData: true },
  { key: "selectList", value: "下拉框多选", requireData: true },
  { key: "date", value: "date(年月日)" },
  { key: "datetime", value: "datetime(日期)" },
  { key: "year", value: "年" },
  { key: "month", value: "年月" },
  { key: "time", value: "time(时间)" },
  { key: "switch", value: "switch(单选)" },
  { key: "textarea", value: "textarea多行" },
  { key: "number", value: "数字(int)" },
  { key: "decimal", value: "小数(decimal)" },
  { key: "checkbox", value: "checkbox" },
  { key: "radio", value: "radio单选", requireData: true },
  { key: "cascader", value: "级联(单选)", requireData: true },
  { key: "treeSelect", value: "树形级联(多选)", requireData: true },
  { key: "editor", value: "富文本编辑器" },
  { key: "mail", value: "邮箱" },
  { key: "phone", value: "手机号" },
  { key: "color", value: "颜色选择器" },
  { key: "img", value: "图片" },
  { key: "excel", value: "excel" },
  { key: "file", value: "文件" },
  { key: "rate", value: "评分" },
  { key: "password", value: "密码输入框" },
];

export const searchDataType = [
  { key: "=", value: "等于" },
  { key: "!=", value: "不等于" },
  { key: "like", value: "%模糊查询%" },
  { key: "likeStart", value: "模糊查询%" },
  { key: "likeEnd", value: "%模糊查询" },
  { key: "textarea", value: "textarea" },
  { key: "switch", value: "switch" },
  { key: "select", value: "select" },
  { key: "selectList", value: "select多选" },
  { key: "year", value: "年" },
  { key: "date", value: "date(年月日)" },
  { key: "datetime", value: "datetime" },
  { key: "month", value: "年月" },
  { key: "time", value: "time" },
  { key: "cascader", value: "级联" },
  { key: "treeSelect", value: "树形级联(多选)" },
  { key: "checkbox", value: "checkbox" },
  { key: "radio", value: "radio" },
  { key: "range", value: "区间查询" },
  { key: "mail", value: "mail" },
  { key: "number", value: "number(数字)" },
  { key: "decimal", value: "decimal(小数)" },
  // { key: 'phone', value: 'phone' }
];
